# This is a TOML document.


#当前使用的环境
[env]
name="moa-demo"
runMode="dev"
#service Uri的后缀可以为空
serviceUriSuffix=""
#可以指定正则表达式也可以直接:13000默认使用0.0.0.0的IP(不建议)^10\\.83\\.\\d+\\.\\d+$:13000
bindAddress=":13000"
#可以是momokeeper或者zookeeper
registryType="momokeeper" 
#registryType="zookeeper" 

#registry的管理	
[registry]
	[registry.dev]
		hosts="localhost:13000"
	[registry.online]
		hosts="vm-bibi-zk-mq001.vm:2181,vm-bibi-zk-mq002.vm:2181,vm-bibi-zk-mq003.vm:2181" 

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		logFile="../conf/log_moa.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
		
	[clusters.online]
		#env=dev/online
		env="online"
		logFile="../conf/log_moa.xml" 
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384
		#写入缓冲大小
		writeBufferSize=16384
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
