#当前使用的环境
[server]
	name="moa-demo"
	runMode="dev"
	#可以指定正则表达式也可以直接:13000默认使用0.0.0.0的IP(不建议)^10\\.83\\.\\d+\\.\\d+$:13000
	bindAddress=":13000"
	groupId="*"
	compress="snappy"

[client]
	name="moa-demo"
	appSecretKey="123"
	runMode="dev"
	compress="snappy"
	selectorStrategy="random"

#cluster的服务器
[clusters]
	[clusters.dev]
		env="dev" 
		registry="zk://localhost:2181"
		logFile="../conf/log.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
		
	[clusters.online]
		env="online"
		registry="zk://vm-bibi-zk-mq001.vm:2181,vm-bibi-zk-mq002.vm:2181,vm-bibi-zk-mq003.vm:2181"
		logFile="../conf/log.xml" 
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384
		#写入缓冲大小
		writeBufferSize=16384
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
